//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTIS_TB
    {
        public int Identifiant { get; set; }
        public string Projet { get; set; }
        public string Résumé { get; set; }
        public Nullable<System.DateTime> Date_de_soumission { get; set; }
        public string P { get; set; }
        public string Rapporteur { get; set; }
        public string Assigné_à { get; set; }
        public string Priorité { get; set; }
        public string Impact { get; set; }
        public string Catégorie { get; set; }
        public Nullable<System.DateTime> Mis_à_jour { get; set; }
        public string Date_résolution { get; set; }
        public string Résolution { get; set; }
        public Nullable<double> Charge_Num { get; set; }
        public string Charge { get; set; }
        public Nullable<double> Conso_Num { get; set; }
        public string Consommé { get; set; }
        public string Statut { get; set; }
        public string TL { get; set; }
        public string Projet_Court { get; set; }
        public string Resp { get; set; }
        public Nullable<double> Week_in { get; set; }
        public Nullable<double> Week_out { get; set; }
        public Nullable<double> Week_update { get; set; }
        public Nullable<double> Year_in { get; set; }
        public Nullable<double> Year_out { get; set; }
        public string Year___Week_in { get; set; }
        public string Year___Week_Out { get; set; }
        public string SLA { get; set; }
        public string SR { get; set; }
        public string evo { get; set; }
        public Nullable<double> Affectation { get; set; }
        public Nullable<double> TimeResol { get; set; }
        public string SLA_EVOL { get; set; }
        public Nullable<double> Month { get; set; }
        public Nullable<double> à_fermer { get; set; }
        public Nullable<double> Abandonnée { get; set; }
        public Nullable<double> Fermée { get; set; }
        public Nullable<System.DateTime> Clos { get; set; }
        public Nullable<double> SLO { get; set; }
        public string Reopen { get; set; }
        public Nullable<double> EvoPriseEnCharge { get; set; }
        public string Domaine { get; set; }
        public string Typologie { get; set; }
        public Nullable<double> M_D { get; set; }
    }
}
